blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),

    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('search/', views.search, name='search'),
]

simpleblog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.post_list, name='post_list'),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('published', 'Published'),
        ('draft', 'Draft'),
    )
    title = models.CharField(max_length=250)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='posts')
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=25,
                              choices=STATUS_CHOICES,
                              default='draft')
    image = models.URLField(blank=True)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[
            self.publish.year,
            self.publish.month,
            self.publish.day,
            self.slug,
        ])

blog/forms.py
from django import forms


class SearchForm(forms.Form):
    query = forms.CharField(max_length=250,
                            widget=forms.TextInput(
                                attrs={
                                    "class": "form-control mr-md-1 semail",
                                    "placeholder": "Enter Search",
                                }
                            ))

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Post
from .forms import SearchForm


def post_list(request):
    form_search = SearchForm()
    home = 'home'

    object_list = Post.published.all()
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post_list.html', {
                      'page': page,
                      'posts': posts,
                      'home': home,
                      'form_search': form_search,
                  })


def post_detail(request, year, month, day, post):
    form_search = SearchForm()
    post = get_object_or_404(Post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day,
                             slug=post)
    return render(request, 'blog/post_detail.html', {
        'post': post,
        'form_search': form_search,
    })


def contact(request):
    contact = 'contact'
    return render(request, 'blog/contact.html', {
        'contact': contact,
    })


def about(request):
    about = 'about'
    return render(request, 'blog/about.html', {
        'about': about,
    })


def search(request):
    form_search = SearchForm()
    query = ''
    results = []
    if 'query' in request.GET:
        form_search = SearchForm(request.GET)
        if form_search.is_valid():
            query = form_search.cleaned_data['query']

    results = Post.published.filter(title__contains=query)

    return render(request, 'blog/search.html', {
        'query': query,
        'results': results,
        'form_search': form_search,
    })

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <title>
        Blog-{% block title %}
        {% endblock %}
    </title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Blog Template">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">

    {% block icon %}
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    {% endblock %}


    <!-- FontAwesome JS-->
    <script defer src="https://use.fontawesome.com/releases/v5.7.1/js/all.js"
        integrity="sha384-eVEQC9zshBn0rFj4+TU78eNA19HMNigMviK/PU/FFjLXqa/GKPgX58rvt5Z8PLs7"
        crossorigin="anonymous"></script>

    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" href="{% static 'assets/css/theme-1.css' %}">

</head>

<body>

    <header class="header text-center">
        <h1 class="blog-name pt-lg-4 mb-0">
            <a href="{% url 'blog:post_list' %}">Landry Blog</a>
        </h1>

        <nav class="navbar navbar-expand-lg navbar-dark">

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation"
                aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div id="navigation" class="collapse navbar-collapse flex-column">
                <div class="profile-section pt-3 pt-lg-0">
                    <img class="profile-image mb-3 rounded-circle mx-auto"
                        src="{% static 'assets/images/author.jpeg' %}" alt="image">

                    <div class="bio mb-3">Hi, my name is Landry Moise.I am fullstack Dev<br>
                        <a href="{% url 'blog:about' %}">Find out more about me</a></div>
                    <!--//bio-->
                    <ul class="social-list list-inline py-3 mx-auto">
                        <li class="list-inline-item"><a href="https://www.facebook.com/landry.onana.752"><i
                                    class="fab fa-facebook fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="https://github.com/landryonana?tab=repositories"><i
                                    class="fab fa-github-alt fa-fw"></i></a></li>
                    </ul>
                    <!--//social-list-->
                    <hr>
                </div>
                <!--//profile-section-->

                <ul class="navbar-nav flex-column text-left">
                    <li class="nav-item {% if home %} active{% endif %}">
                        <a class="nav-link" href="{% url 'blog:post_list' %}">
                            <i class="fas fa-home fa-fw mr-2"></i>
                            Home
                            <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item {% if contact %} active{% endif %}">
                        <a class="nav-link" href="{% url 'blog:contact' %}">
                            <i class="fas fa-bookmark fa-fw mr-2"></i>
                            Contact</a>
                    </li>
                    <li class="nav-item {% if about %}active{% endif %}">
                        <a class="nav-link" href=" {% url 'blog:about' %}">
                            <i class="fas fa-user fa-fw mr-2"></i>
                            About
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <div class="main-wrapper">
        <section class="cta-section theme-bg-light py-5">
            <div class="container text-center">
                {% block welcome %}
                <h2 class="heading" style="text-align: center;">Welcome to my blog</h2>
                {% endblock %}

                {% block search %}
                {% include 'search.html' %}
                {% endblock %}

            </div>
            <!--//container-->
        </section>

        <!--content=====================================================================-->
        {% block content %}

        {% endblock %}
        <!--end content=====================================================================-->

        <footer class="footer text-center py-2 theme-bg-dark">

            <!--/* This template is released under the Creative Commons Attribution 3.0 License. Please keep the attribution link below when using for your own project. Thank you for your support. :) If you'd like to use the template without the attribution, you can buy the commercial license via our website: themes.3rdwavemedia.com */-->
            <small class="copyright">copyright
                <i class="fas fa-heart" style="color: #fb866a;"></i>for developers</small>

        </footer>

    </div>
    <!--//main-wrapper-->

    <!-- Javascript -->
    <script src="{% static 'assets/plugins/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/plugins/popper.min.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Style Switcher (REMOVE ON YOUR PRODUCTION SITE) -->
    <script src="{% static 'assets/js/demo/style-switcher.js' %}"></script>


</body>

</html>

templates/blog/about.html
{% extends 'base.html' %}

{% block title %}
About
{% endblock %}


{% block search %}
{% endblock %}

{% block welcome %}
<h2 class="heading" style="text-align: center;">About</h2>
{% endblock %}

{% load static %}
{% block content %}
<h3 class="heading" style="text-align: center;">About Me</h3>
<article class="about-section py-5">
    <div class="container">
        <p>My name is Landry I'm fullstack Dev. I love to developpe web application,desktop app</p>
        <figure><img class="img-fluid" src="{% static 'assets/images/author.jpeg' %}" alt="image"></figure>
    </div>
</article>

<h3 class="heading" style="text-align: center;">About Blog</h3>
<article class="about-section py-5">
    <div class="container">
        <p>this blog is dev with django framework</p>
    </div>
</article>
{% endblock %}

templates/blog/contact.html
{% extends 'base.html' %}

{% block title %}
Contact
{% endblock %}

{% block search %}
{% endblock %}

{% block welcome %}
<h2 class="heading" style="text-align: center;">Contact Information</h2>
{% endblock %}

{% block content %}
<article class="about-section py-5">
    <div class="container">
        <section class="ftco-section contact-section px-md-4">
            <div class="container">
                <div class="row d-flex mb-5 contact-info">
                    <div class="col-md-12 mb-4">
                    </div>
                    <div class="w-100"></div>
                    <div class="col-lg-6 col-xl-3 d-flex mb-4">
                        <div class="info bg-light p-4">
                            <p><span>Address:</span> Cameroun-Yaoundé Nkolbisson</p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xl-3 d-flex mb-4">
                        <div class="info bg-light p-4">
                            <p><span>Phone:</span> <a href="tel://237699806665">+ 237699806665</a></p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xl-3 d-flex mb-4">
                        <div class="info bg-light p-4">
                            <p><span>Email:</span> <a href="mailto:lndronana@gmail.com">lndronana@gmail.com</a></p>
                        </div>
                    </div>
                </div>

            </div>
        </section>

    </div>
</article>
{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block icon %}
<link rel="shortcut icon" href="{{post.image}}">
{% endblock %}

{% block content %}
<article class="blog-post px-3 py-5 p-md-5">
    <div class="container">
        <header class="blog-post-header">
            <h2 class="title mb-2">{{ post.title }}</h2>
            <div class="meta mb-3"><span class="date">Published {{ post.publish }}</span></div>
        </header>

        <div class="blog-post-body">
            <figure class="blog-banner">
                <img class="img-fluid" src="{% if post.image %}{{post.image}}
            {% else %} {% static 'assets/images/no_image.png' %} {% endif %}" alt="{{ post.title }}">
            </figure>
            <p>{{ post.body|linebreaks }} </p>
        </div>
    </div>
</article>
{% endblock %}

templates/blog/post_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Home
{% endblock %}

{% block content %}
<section class="blog-list px-3 py-5 p-md-5">
    <div class="container">

        {% for post in posts %}
        <div class="item mb-5">
            <div class="media">
                <img class="mr-3 img-fluid post-thumb d-none d-md-flex" src="
                    {% if post.image %}
                        {{post.image}}
                    {% else %}
                    {% static 'assets/images/no_image.png' %}
                    {% endif %}" alt="image">
                <div class="media-body">
                    <h3 class="title mb-1"><a href="{{ post.get_absolute_url }}">
                            {{ post.title }}</a>
                    </h3>
                    <div class="meta mb-1"><span class="date">Published {{ post.publish }}</span><span
                            class="time"></span></div>
                    <div class="intro">{{ post.body|linebreaks|truncatewords:30 }}</div>
                    <a class="more-link" href="{{ post.get_absolute_url }}">Read more &rarr;</a>
                </div>
            </div>
        </div>
        {% empty %}
        <p>No Post found</p>
        {% endfor %}

        {% include 'pagination.html' with page=posts %}

    </div>
</section>

{% endblock %}

templates/blog/search.html
{% extends 'base.html' %}

{% block title %}
search of {{ query }}
{% endblock %}

{% block welcome %}
<div style="text-align: center;">
    <h2 class="heading">
        Results of "{{ query }}"
    </h2>
    <p>Found {{ results.count }}</p>
</div>
{% endblock %}

{% load static %}
{% block content %}
<section class="blog-list px-3 py-5 p-md-5">
    <div class="container">
        {% for post in results %}
        <div class="item mb-5">
            <div class="media">
                <img class="mr-3 img-fluid post-thumb d-none d-md-flex" src="
                    {% if post.image %}
                        {{post.image}}
                    {% else %}
                    {% static 'assets/images/no_image.png' %}
                    {% endif %}" alt="image">
                <div class="media-body">
                    <h3 class="title mb-1"><a href="{{ post.get_absolute_url }}">
                            {{ post.title }}</a>
                    </h3>
                    <div class="meta mb-1"><span class="date">Published {{ post.publish }}</span><span
                            class="time"></span>
                    </div>
                    <div class="intro">{{ post.body|linebreaks|truncatewords:30 }}</div>
                    <a class="more-link" href="{{ post.get_absolute_url }}">Read more &rarr;</a>
                </div>
            </div>
        </div>
        {% empty %}
        <p style="text-align: center;">No Post found</p>
        {% endfor %}
    </div>
</section>
{% endblock %}

templates/pagination.html
<nav class="blog-nav nav nav-justified my-5">

    {% if page.has_previous %}
    <a class="nav-link-prev nav-item nav-link rounded-left" href="?page={{ page.previous_page_number }}">
        Previous
        <i class="arrow-prev fas fa-long-arrow-alt-left"></i>
    </a>
    {% endif %}

    {% if page.has_next %}
    <a class="nav-link-next nav-item nav-link rounded" href="?page={{ page.next_page_number }}">
        Next
        <i class="arrow-next fas fa-long-arrow-alt-right"></i></a>
    {% endif %}

</nav>

templates/search.html
<form method="GET" action="{% url 'blog:search' %}" class="signup-form form-inline justify-content-center pt-3">
    <div class="form-group">
        {{ form_search.query }}
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
</form>